import vk_api
from vk_api.keyboard import VkKeyboard, VkKeyboardColor #клавиатура(кнопки)

class KeyboardOfSubjects:
    vkKey = VkKeyboard(one_time=False, inline = True)  # one_time=True чтобы клавиатура исчезла после нажатия
    vkKey.add_button("Програмирование на языке Питон", VkKeyboardColor.SECONDARY)
    vkKey.add_button("Экономическая культура", VkKeyboardColor.SECONDARY)
    vkKey.add_line()
    vkKey.add_button("Теория вероятностей", VkKeyboardColor.SECONDARY)
    vkKey.add_button("ИССУК", VkKeyboardColor.SECONDARY)
    vkKey.add_line()
    vkKey.add_button("Проектирование баз данных", VkKeyboardColor.SECONDARY)
    vkKey.add_button("Програмирование на языке Питон", VkKeyboardColor.SECONDARY)
    vkKey.add_line()
    vkKey.add_button("Програмирование на языке Питон", VkKeyboardColor.SECONDARY)
    vkKey.add_button("Экономическая культура", VkKeyboardColor.SECONDARY)
    vkKey.add_line()
    vkKey.add_button("Теория вероятностей", VkKeyboardColor.SECONDARY)
    vkKey.add_button("ИССУК", VkKeyboardColor.SECONDARY)
    vkKey1 = VkKeyboard(one_time = False, inline = True)
    vkKey1.add_button("Програмирование на языке Питон", VkKeyboardColor.SECONDARY)
    vkKey1.add_button("Экономическая культура", VkKeyboardColor.SECONDARY)
    vkKey1.add_line()
    vkKey1.add_button("Теория вероятностей", VkKeyboardColor.SECONDARY)
    vkKey1.add_button("ИССУК", VkKeyboardColor.SECONDARY)
    vkKey1.add_line()
    vkKey1.add_button("Проектирование баз данных", VkKeyboardColor.SECONDARY)
    vkKey1.add_button("Програмирование на языке Питон", VkKeyboardColor.SECONDARY)
    vkKey1.add_line()
    vkKey1.add_button("Програмирование на языке Питон", VkKeyboardColor.SECONDARY)
    vkKey1.add_button("Экономическая культура", VkKeyboardColor.SECONDARY)
    vkKey1.add_line()
    vkKey1.add_button("Теория вероятностей", VkKeyboardColor.SECONDARY)
    vkKey1.add_button("ИССУК", VkKeyboardColor.SECONDARY)